
/*
 表单
 */
export const FORM_ID_VALUE = 'FORM_ID_VALUE';
export const FORM_COVER_VALUE = 'FORM_COVER_VALUE';
export const FORM_TITLE_VALUE = 'FORM_TITLE_VALUE';
export const FORM_SUBTITLE_VALUE = 'FORM_SUBTITLE_VALUE';
export const FORM_DESCRIPTION_VALUE = 'FORM_DESCRIPTION_VALUE';
export const FORM_CATEGORY_VALUE = 'FORM_CATEGORY_VALUE';
export const FORM_TAGS_VALUE = 'FORM_TAGS_VALUE';


/*
 工具栏
 */
export const TOOLBAR_LINK_MODAL_VISIBLE = 'TOOLBAR_LINK_MODAL_VISIBLE';
export const TOOLBAR_IMAGE_MODAL_VISIBLE = 'TOOLBAR_IMAGE_MODAL_VISIBLE';
export const TOOLBAR_EMBED_MODAL_VISIBLE = 'TOOLBAR_EMBED_MODAL_VISIBLE';
export const TOOLBAR_SETTING_MODAL_VISIBLE = 'TOOLBAR_SETTING_MODAL_VISIBLE';


/*
 编辑区域
 */
export const EDITABLE_EDITOR_STATE = 'EDITABLE_EDITOR_STATE';
export const EDITABLE_EDITOR_READONLY = 'EDITABLE_EDITOR_READONLY';
export const EDITABLE_IMAGE_REMARK_BLOCK_ADD = 'EDITABLE_IMAGE_REMARK_BLOCK_ADD';
export const EDITABLE_IMAGE_REMARK_BLOCK_DELETE = 'EDITABLE_IMAGE_REMARK_BLOCK_DELETE';
